version: '3.5'

volumes:
  data:
  letsencrypt:
  #bundler_gems:

services:
  db:
    container_name: postgresql
    image: postgres:14
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - data:/var/lib/postgresql/data
      - type: tmpfs
        target: /data/shm
  web:
    build: .
    container_name: rails-app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' && rails db:setup"
    volumes:
      - .:/rails-app
      #- bundler_gems:usr/local/bundle/
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
    restart: unless-stopped
