
name: "Ruby on Rails CI"

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build application
        working-directory: ./aplicacao
        run: docker-compose up -d

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby 3.0.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: Install rubocop
        working-directory: ./aplicacao
        run: gem install rubocop
      - name: Run rubocop
        working-directory: ./aplicacao
        run: rubocop -A --fail-level F
        
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        working-directory: ./aplicacao
        run: docker-compose run web bash -c "rails db:reset; rspec"

  push-to-docker-hub:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker push
        env:
         DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
         DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
         IMAGE: estevaoreis/bibliotecaRails:${{ github.sha }}
       run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
         docker build -t $IMAGE .
         docker push $IMAGE