
name: "Ruby on Rails CI"

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build application
        working-directory: ./aplicacao
        run: docker-compose up -d

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby 3.0.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: Run rubocop
        run: docker-compose run app bash -c "gem install rubocop; rubocop -l --fail-level F"
        
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: docker-compose run app bash -c "rails db:reset; rspec"